# Form implementation generated from reading ui file 'ui/limites_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(881, 172)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setObjectName("label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label)
        self.input_nome = QtWidgets.QLineEdit(parent=Dialog)
        self.input_nome.setObjectName("input_nome")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.input_nome)
        self.label_2 = QtWidgets.QLabel(parent=Dialog)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_2)
        self.combo_grandeza = QtWidgets.QComboBox(parent=Dialog)
        self.combo_grandeza.setObjectName("combo_grandeza")
        self.combo_grandeza.addItem("")
        self.combo_grandeza.addItem("")
        self.combo_grandeza.addItem("")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.combo_grandeza)
        self.label_3 = QtWidgets.QLabel(parent=Dialog)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_3)
        self.spin_limite = QtWidgets.QDoubleSpinBox(parent=Dialog)
        self.spin_limite.setObjectName("spin_limite")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.spin_limite)
        self.check_ativa = QtWidgets.QCheckBox(parent=Dialog)
        self.check_ativa.setObjectName("check_ativa")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.ItemRole.LabelRole, self.check_ativa)
        self.verticalLayout.addLayout(self.formLayout)
        self.button_box = QtWidgets.QDialogButtonBox(parent=Dialog)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Save)
        self.button_box.setObjectName("button_box")
        self.verticalLayout.addWidget(self.button_box)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Nome da Regra:"))
        self.label_2.setText(_translate("Dialog", "Grandeza:"))
        self.combo_grandeza.setItemText(0, _translate("Dialog", "Corrente"))
        self.combo_grandeza.setItemText(1, _translate("Dialog", "Tensão"))
        self.combo_grandeza.setItemText(2, _translate("Dialog", "Potência"))
        self.label_3.setText(_translate("Dialog", "Limite Máximo:"))
        self.check_ativa.setText(_translate("Dialog", "Ativa;"))
